[docs] Introducing OpenBAS Agent (Executor)
OpenBAS-Platform/docs pull request #23
Opened 2024-06-14 14:59 UTC by Christian-DONGMO

Init the documentation of this part

2024-06-17 06:15 UTC, RomuDeuxfois requested changes

2024-06-17 06:15 UTC, RomuDeuxfois commented on docs/administration/openbas-agent.md
> +and doesn't suppress completely all files and directories (Windows environment)
Do you think it's a good idea to write agent-related issues in the public documentation instead of trying to resolve them internally?

2024-06-17 08:30 UTC, Christian-DONGMO commented on docs/administration/openbas-agent.md
> +and doesn't suppress completely all files and directories (Windows environment)
You right. I created two issues to store them [isuue 7](https://github.com/OpenBAS-Platform/agent/issues/7) and [issue 8](https://github.com/OpenBAS-Platform/agent/issues/8)

2024-06-20 08:58 UTC, Jipegien requested changes

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +The openBAS agent is an application whose main role is to enroll an asset on the OpenBAS platform,
```suggestion
The openBAS agent is an application whose main role is to enroll an Asset on the OpenBAS platform,

```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +to retrieve jobs or scripts to be executed and to transmit this information to the implants (subject to come)
```suggestion
to retrieve jobs or scripts to be executed and to transmit this information to Implants (subject to come)

```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +for execution on the host asset.
```suggestion
for execution on the host Asset.

```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +The agent will not perform direct attack to remain neutral for antivirus.
```suggestion
The Agent will not perform direct actions on the Asset to remain neutral for antivirus and ensure the full run of the simulation.

```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +It aims to be able to be run on different OS (Windows, Linux, macOS). It is developed in Rust
```suggestion
The OpenBAS Agent is compatible with different OS (Windows, Linux, macOS) and is developed in Rust.
```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +The main features of the OpenBAS agent are:
```suggestion
The main features of the OpenBAS Agent are:

```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +  The agent is installed on the asset using an agent-installer.exe file and runs as a service.
```suggestion
  The agent is installed on the Asset using an agent-installer.exe file and runs as a service.

```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +  For the moment, jobs are implant launches on the asset to be able to execute attacks.
```suggestion
  For the moment, jobs are Implant to spawn and launch on the Asset, waiting to execute payloads of your Simulation's Injects. 

```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +  The agent deletes implants that have been running for a predefined time and cleans the execution directories.
```suggestion
  The Agent deletes Implants that have been running for a predefined time and cleans the execution directories.

```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +  The agent pings the OpenBAS instance every 2 minutes to notify it of its healthy status.
```suggestion
  The Agent pings the OpenBAS instance every 2 minutes to notify it of its healthy status.

```

2024-06-20 08:58 UTC, Jipegien commented on docs/administration/openbas-agent.md
> +  The agent ensures that the processes it has executed are correctly finished or deleted if necessary.
```suggestion
  The Agent ensures that the processes it has executed are correctly finished or deleted if necessary. 

```

2024-07-05 07:02 UTC, RomuDeuxfois approved these changes

2024-07-05 11:33 UTC, merged