[docs] Adding import xls documentation
OpenBAS-Platform/docs pull request #28
Opened 2024-07-23 23:45 UTC by Dimfacion

2024-07-24 05:54 UTC, RomuDeuxfois commented on docs/usage/scenario_import.md
> +The first thing to define in this representation is the matching type in the xls. This is the value that will define which inject to create when scanning the column defined in "inject type column". F
I am not sure to understand that part

"You can choose a word that has nothing to do with the inject type"

I understand what you mean but it seems confusing when I read it. Maybe iy's better to remove it and let just the regular explanation

2024-07-24 07:56 UTC, Dimfacion commented on docs/usage/scenario_import.md
> +The first thing to define in this representation is the matching type in the xls. This is the value that will define which inject to create when scanning the column defined in "inject type column". F
Yeah, I think you're right, I added this phrase in an earlier version where it wasn't very clear but should have removed it when I reworked this part.

2024-07-24 15:49 UTC, Jipegien requested changes

2024-07-24 15:49 UTC, Jipegien commented on docs/usage/scenario_import.md
> +Recreating [injects](injects.md) that were already defined in a spreadsheet can be a frustrating task. To help users save time, we added the possibility to import injects as defined in an xls file in
```suggestion
Recreating a timeline of [injects](injects.md) that were already defined in a spreadsheet can be a frustrating task. To help users save time, we added the possibility to import injects defined in an xls file into a [scenario](scenario.md). This is done via a two-steps process : [creating a mapper](#how-to-create-a-mapper) and [importing the xls file using the mapper](#how-to-import-injects-into-a-scenario-using-a-mapper).
```

2024-07-24 15:49 UTC, Jipegien commented on docs/usage/scenario_import.md
> +Please, do note that if you wish to use only hour of the day (e.g. 9:30) in your trigger time, you need to set a launch date on your scenario.
```suggestion
Please, do note that if you wish to use exact time of the day (e.g. 9:30) in your trigger time, you will need to set a launch date on your scenario before importing the timeline of injects from the xls file.
```

2024-07-24 15:49 UTC, Jipegien commented on docs/usage/scenario_import.md
> +This means that if you want your inject to start 2 days, 3 hours and 45 minutes after the start of your scenario, you can set the trigger time to D+2 H+3 M+45. When using relative dates, keep in mind
```suggestion
This means that if you want your inject to start 2 days, 3 hours and 45 minutes after the start of your scenario, you can set the trigger time to D+2 H+3 M+45. When using relative dates, you do not need to define a pattern for the trigger time field.
```

2024-07-24 15:49 UTC, Jipegien commented on docs/usage/scenario_import.md
> +Once you have set all the fields you wish to set, you can click on the create button if you wish to create your mapper but you can also click on the test button to check that it works as intended.
```suggestion
Once you have set all fields you wish to set, you can click on the create button if you wish to create your mapper but you can also click on the test button to check that it works as intended.
```

2024-07-25 12:24 UTC, Jipegien approved these changes

2024-07-25 12:38 UTC, merged