Add expiration time in expectations page
OpenBAS-Platform/docs pull request #42
Opened 2024-09-30 14:18 UTC by johanah29

2024-09-30 14:22 UTC, RomuDeuxfois requested changes

2024-09-30 14:22 UTC, RomuDeuxfois commented on docs/usage/expectations.md
> +- In the application.properties file
We should mention the Docker file instead of the application.properties file
User use a docker image to deploy

2024-09-30 14:22 UTC, EllynBsc commented on docs/usage/expectations.md
> +When creating an expectation, users can set expiration time. The system's default times are set on the form and users can change it or not.
When creating an expectation, users can set an expiration time. The system's default times are set on the form and users decide to override it.

2024-09-30 14:23 UTC, EllynBsc commented on docs/usage/expectations.md
> +When creating an expectation, users can set expiration time. The system's default times are set on the form and users can change it or not.
```suggestion
When creating an expectation, users can set expiration time. The system's default times are set on the form and users can change it or not.
```

2024-09-30 16:37 UTC, RomuDeuxfois commented on docs/usage/expectations.md
> +
```suggestion
- In the Docker .env file thanks to this variables
| Parameter                                       | Environment variable                            | Default value      | Description                                                            |
|:------------------------------------------------|:------------------------------------------------|:-------------------|:-----------------------------------------------------------------------|
| openbas.expectation.technical.expiration-time   | OPENBAS_EXPECTATION_TECHNICAL_EXPIRATION-TIME   | 21600              | Expiration time for Technical expectation (detection & prevention)      |
| openbas.expectation.detection.expiration-time   | OPENBAS_EXPECTATION_DETECTION_EXPIRATION-TIME   | 21600              | Expiration time for detection expectation                               |
| openbas.expectation.prevention.expiration-time  | OPENBAS_EXPECTATION_PREVENTION_EXPIRATION-TIME  | 21600              | Expiration time for prevention expectation                              |
| openbas.expectation.human.expiration-time       | OPENBAS_EXPECTATION_HUMAN_EXPIRATION-TIME       | 86400              | Expiration time for human expectation (manual, challenge & article)     |
| openbas.expectation.challenge.expiration-time   | OPENBAS_EXPECTATION_CHALLENGE_EXPIRATION-TIME   | 86400              | Expiration time for challenge expectation                               |
| openbas.expectation.article.expiration-time     | OPENBAS_EXPECTATION_ARTICLE_EXPIRATION-TIME     | 86400              | Expiration time for article expectation                                 |
| openbas.expectation.manual.expiration-time      | OPENBAS_EXPECTATION_MANUAL_EXPIRATION-TIME      | 86400              | Expiration time for manual expectation                                  |

```

2024-10-03 12:43 UTC, RomuDeuxfois approved these changes

2024-10-03 12:44 UTC, merged