[docs] add simulation report page
OpenBAS-Platform/docs pull request #48
Opened 2024-10-21 13:37 UTC by MarineLeM

Add simulation report page

2024-10-21 14:54 UTC, EllynBsc commented on docs/usage/simulation_reports.md
> +* Open the Report Drawer: Click the "Edit" button located on the right side of the page, then select "Access Reports"
```suggestion
* Open the Report Drawer: Click on the "Edit" button located on the right side of the page, then select "Access Reports"
```

2024-10-21 14:55 UTC, EllynBsc commented on docs/usage/simulation_reports.md
> +1. At the bottom of the report list in the drawer, click the "Add" button to create a new report.
```suggestion
1. At the bottom of the report list in the drawer, click on the "Add" button to create a new report.
```

2024-10-21 14:57 UTC, EllynBsc requested changes
Hi @MarineLeM 👋 

Nice! Very clear, tiny english idioms but LGTM 🚀

2024-10-24 13:39 UTC, EllynBsc approved these changes

2024-10-24 13:41 UTC, MarineLeM commented
@EllynBsc ready for a second round

2024-10-24 16:15 UTC, merged