[docs] Update dashboard documentation
OpenBAS-Platform/docs pull request #49
Opened 2024-10-22 13:45 UTC by RomuDeuxfois

2024-10-25 07:33 UTC, EllynBsc commented on docs/usage/evaluate/overview.md
> +![metric cards](assets/metric-cards.png)
Here @RomuDeuxfois, we have 4 metrics in 4 different cards no ? Not clear to me
- Scenarios
- Simulations
- Players
- Assets

2024-10-25 07:39 UTC, EllynBsc commented on docs/usage/getting-started.md
> +meaningful attack scenario based on real threat. OpenBAS is result-oriented with many dashboard helping you to evaluate
```suggestion
meaningful attack scenarios based on real threat. OpenBAS is result-oriented with many dashboards helping you to evaluate
```

2024-10-25 07:42 UTC, EllynBsc commented on docs/usage/getting-started.md
> +The Home screen gives any visitor on the OpenBAS platform an outlook on the live of the platform as well as an overview
```suggestion
The Home screen provides every OpenBAS platform visitor with a snapshot of the platform activity as well as an overview 
```

2024-10-25 07:44 UTC, EllynBsc commented on docs/usage/getting-started.md
> +The [Caldera agent](inject-caldera.md) will allow you to play various technical events, based on the Mitre ATT&CK
Here should we mention the Mitre ATT&CK doc  - https://attack.mitre.org/

2024-10-25 07:46 UTC, EllynBsc commented on docs/usage/getting-started.md
> +[Scenarios](scenario.md) act as template for your Breach and Attack simulations. After establihing such a template, you
```suggestion
[Scenarios](scenario.md) act as template for your Breach and Attack simulations. After establishing such a template, you
```

2024-10-25 07:47 UTC, EllynBsc commented on docs/usage/getting-started.md
> +Optionnaly, you can buff up your scenario by
```suggestion
Optionally, you can enhance your scenario by
```

2024-10-25 07:48 UTC, EllynBsc commented on docs/usage/getting-started.md
> +On time, a Simulation based on your Scenario template is generated. it is listed in your Scenario overview and in the
```suggestion
On time, a Simulation based on your Scenario template is generated. It is listed in your Scenario overview and in the
```

2024-10-25 07:49 UTC, EllynBsc commented on docs/usage/getting-started.md
> +Simulations menu. Fron there, you can follow the course of the Simulation and interact with it, for example to validate
```suggestion
Simulations menu. From there, you can follow the course of the Simulation and interact with it, for example to validate
```

2024-10-25 07:54 UTC, EllynBsc requested changes
Hey @RomuDeuxfois 👋 

Just the metric cards part not clear to me as we have 4 metrics and not 2, but maybe there is something I haven't grasped properly.

Very clear documentation updates, thanks for that 🚀

2024-10-29 14:54 UTC, RomuDeuxfois commented on docs/usage/evaluate/overview.md
> +![metric cards](assets/metric-cards.png)
I tried to be cleared

2024-10-29 14:59 UTC, RomuDeuxfois commented
I made the changes

2024-10-29 15:37 UTC, EllynBsc approved these changes

2024-10-29 16:14 UTC, merged