[docs] Update OpenBAS x OpenCTI integration
OpenBAS-Platform/docs pull request #50
Opened 2024-10-24 13:48 UTC by RomuDeuxfois

2024-10-25 07:21 UTC, EllynBsc commented on docs/usage/scenario/opencti_scenario.md
> +When you click the simulate button, you’ll have two options:
```suggestion
When you click on the simulate button, you’ll have two options:
```

2024-10-25 07:21 UTC, EllynBsc commented on docs/usage/scenario/opencti_scenario.md
> +It’s essential to understand that scenario creation for these entities relies on matching TTPs between OpenCTI and
```suggestion
It’s essential to understand that a scenario creation for these entities relies on matching TTPs between OpenCTI and
```

2024-10-25 07:24 UTC, EllynBsc commented on docs/usage/scenario/opencti_scenario.md
> +Once you've finalized the scenario, you can schedule your simulation as you would for any other scenario. The overall
```suggestion
Once you've finalized the scenario, you can schedule your simulation as you would do for any other scenario. The overall
```

2024-10-25 07:26 UTC, EllynBsc requested changes
Hey @RomuDeuxfois 👋 

Really nice!

2024-10-29 13:59 UTC, RomuDeuxfois commented
@EllynBsc  I added all your changes :)
Thanks for the review !

2024-10-29 15:39 UTC, EllynBsc approved these changes

2024-10-29 16:14 UTC, merged